config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new', as: :login
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/session', to: 'sessions#destroy', as: :session_delete
  resources :resources, only: :index
  resource :users do 
    resources :emergency_contacts
    resources :trips
  end

  resources :areas, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  helper_method :logged_in?

  private

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  include ApplicationHelper

  def index
    @areas = AreaFacade.all_zones
    if current_user.nil?
      @area = AreaFacade.find_zone(1128)
    else
      @area = AreaFacade.find_zone(current_user.favorite_zone)
    end
  end

  def show
    @areas = AreaFacade.all_zones
    @area = AreaFacade.find_zone(params[:id])
  end
end

app/controllers/emergency_contacts_controller.rb
class EmergencyContactsController < ApplicationController

  def edit
    @user = current_user
    @contact = UserFacade.one_contact(@user.id, params[:id])
  end

  def new
    @user = current_user
  end

  def create
    response = UserService.create_emergency_contact(params)
    if response.success?
      redirect_to edit_users_path
    else
      flash[:error] = 'Something went wrong'
      render :new
    end
  end

  def update
    response = UserFacade.update_one_contact(params)
    if !response.nil?
      flash[:success] = 'Emergency Contact updated'
      @contact = response
      redirect_to edit_users_path
    else
      flash[:error] = 'Something went wrong'
      render :edit
    end
  end

  def destroy
    UserService.delete_contact(params[:id], params[:contact_id])
    if response.successful?
      flash[:success] = 'Emergency contact deleted'
      redirect_to edit_users_path
    else
      flash[:error] = 'Something went wrong'
      render :edit
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
    if logged_in?
      redirect_to users_path
    end
  end

  def create
    user = UserFacade.find_or_create_user(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to users_path
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :logged_in_user
  include ApplicationHelper

  def new
    @user_trips = user_trips
    @user = current_user
  end

  def edit
    @user = current_user
    @user_trips = user_trips
    @trip = @user_trips.select { |trip| trip.id == params[:id].to_i }[0]
  end

  def update
    @user_trips = user_trips
    @trip = @user_trips.select { |trip| trip.id == params[:id].to_i }[0]

    response = UserService.update_trip(params)
    if response != nil
      redirect_to users_trip_path(@trip.id)
    else
      redirect_to edit_users_trip_path(@trip.id)
      flash[:error] = 'Unable to update trip. Try Again.'
    end
  end

  def create
    response = UserService.create_trip(params)
    if response.success?
      redirect_to users_path
    else
      flash[:error] = 'Something went wrong'
      render :new
    end
  end

  def show
  @user_trips = user_trips
    @trip = @user_trips.select do |trip| #does this make two calls???
      trip.id == params[:id].to_i
    end[0]
    @area = AreaFacade.find_zone(@trip.zone_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :logged_in_user, only: :show

  def show
    @user = current_user
    @user_trips = user_trips
    @area = AreaFacade.find_zone(@user.favorite_zone)
  end


  def edit
    @user = current_user
    @emergency_contacts = UserFacade.emergency_contacts(@user.id)
  end


  def update
    response = UserService.update_user(params)
    if !response.nil?
      redirect_to edit_users_path
      flash[:success] = 'Favorite zone updated'
    else
      flash[:error] = 'Something went wrong'
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avalanche_zones
    [
      ['Olympics', 1128],
      ['West Slopes North', 1129],
      ['West Slopes Central', 1130],
      ['West Slopes South', 1131],
      ['Stevens Pass', 1132],
      ['Snoqualmie Pass', 1136],
      ['East Slopes North', 1137],
      ['East Slopes Central', 1138],
      ['East Slopes South', 1139],
      ['Mt Hood', 1140]
    ]
  end

  def user_trips
    UserFacade.user_trips(session[:user_id])
  end

  def zone_id_to_name(zone_id)
    {
      1128 => 'Olympics',
      1129 => 'West Slopes North',
      1130 => 'West Slopes Central',
      1131 => 'West Slopes South',
      1132 => 'Stevens Pass',
      1136 => 'Snoqualmie Pass',
      1137 => 'East Slopes North',
      1138 => 'East Slopes Central',
      1139 => 'East Slopes South',
      1140 => 'Mt Hood',
      88 => 'MT 88 [TEST]'
    }[zone_id]
  end

  def flash_class(level)
    case level
        when 'notice' then "alert alert-primary"
        when 'success' then "alert alert-success"
        when 'error' then "alert alert-danger"
        when 'alert' then "alert alert-secondary"
    end
  end

end

app/helpers/emergency_contacts_helper.rb
module EmergencyContactsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if session[:user_id]
      @user ||= UserFacade.get_user(session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/areas/index.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"></svg>
      <span class="fs-4 d-flex align-items-center mb-3 mb-md-0 me-md-auto">Zones</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
     <% @areas.each do |area| %>
      <li class="nav-item">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          <%= link_to area.name, area_path(area.id), class: "nav-link active"  %>
      </li>
      <% end %>
    </ul>
  </div>

<%= render 'shared/area_detailed' %>
<%= render 'shared/zone_weather_forecast' %>

app/views/areas/show.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"></svg>
      <span class="fs-4 d-flex align-items-center mb-3 mb-md-0 me-md-auto">Zones</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
     <% @areas.each do |area| %>
      <li class="nav-item">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          <%= link_to area.name, area_path(area.id), class: "nav-link active"  %>
      </li>
      <% end %>
    </ul>
  </div>

<%= render 'shared/area_detailed' %>
<%= render 'shared/zone_weather_forecast' %>

app/views/emergency_contacts/edit.html.erb
<main class="px-3">
  <div class="cover-container d-flex p-3 mx-auto flex-column">
    <h1>Edit <%= @contact.name %>'s info </h1>
  </div>
<br>

  <div class="row">
    <div class="container col-lg-10 card-bg p-3">
      <%= form_with url: users_emergency_contact_path(user_id: @user.id), method: :patch, local: true do |f| %>
          <div class="mb-3">
            <%= f.label :name, { class: "form-label fw-bold"}%>
            <%= f.text_field :name, value: @contact.name, class: "form-control"%>
          </div>

          <div class="mb-3">
            <%= f.label :phone_number, { class: "form-label fw-bold"} %>
            <%= f.telephone_field :phone_number, maxlength: 10, value: @contact.phone_number, class: "form-control"%>

          </div>
            <%= f.submit 'Update', {class: "btn btn-lg btn-secondary border-white bg-black"} %>
      <% end %>
      </div>
    </div>


</main>

app/views/emergency_contacts/new.html.erb
<main class="px-3">
  <div class="cover-container d-flex p-3 mx-auto flex-column">
    <h1> Add Emergency Contact</h1>
  </div>

  <div class="row">
    <div class="container col-lg-10 card-bg p-3">
      <%= form_with url: users_emergency_contacts_path, local: true do |f| %>
      <%# <div class="card mb-3">
        <div class="card-body"> %>
        <%= f.hidden_field :user_id, value: @user.id %>

        <div class="mb-3">
          <%= f.label :name, { class: "form-label fw-bold"} %>
          <%= f.text_field :name, { class: "form-control"}%>
        </div>

        <div class="mb-3">
          <%= f.label :phone_number, { class: "form-label fw-bold"} %>
          <%= f.telephone_field :phone_number, maxlength: 10, class: "form-control" %>
        </div>

        <%= f.submit 'Create', {class: "btn btn-lg btn-secondary border-white bg-black"}%>
        <%# </div>
      </div> %>
      <% end %>
    </div>
  </div>
</main>

app/views/landing/index.html.erb
<%= button_to "Log in with Google", '/auth/google_oauth2'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlakesOfWrathFe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= javascript_include_tag 'application' %>
    <link href="custom.css" rel="stylesheet">

  </head>

  <body>
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <% if logged_in? %>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to 'Dashboard', users_path, class: "nav-link px-2 text-white" %></li>
            <li><%= link_to 'Profile', edit_users_path, class: "nav-link px-2 text-white" %></li>
            <li><%= link_to 'Resources', resources_path, class: "nav-link px-2 text-white" %></li>
            <li><%= link_to 'Forecast', areas_path, class: "nav-link px-2 text-white" %></li>
          </ul>
          <div class="text-end">
            <%= button_to "Log Out", '/session', method: :delete, class: "btn btn-outline-light me-2"  %>
          </div>
        <% else %>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to 'Resources', resources_path, class: "nav-link px-2 text-white" %></li>
            <li><%= link_to 'Forecast', areas_path, class: "nav-link px-2 text-white" %></li>
          </ul>

          <div class="text-end">
            <%= button_to "Log in", '/auth/google_oauth2', class: "btn btn-warning"  %>
          </div>
        <% end %>
      </div>
    </div>
  </header>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
          <%= value %>
    </div>
  <% end %>
  <div 
    class="masthead"
    style="background-image: url('bg-image.jpg');">
    <div class="color-overlay d-flex justify-content-center align-items-top">
        <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/resources/index.html.erb
<main>
    <div class="p-5 mb-4 rounded-3">
      <div class="container-fluid py-1">
        <h1 class="display-5 fw-bold">Get your local forecast</h1>
        <p class="col-md-8 fs-4">Winter backcountry travel is inherently dangerous.  Flakes of Wrath is just
one tool to help you stay safer. Your local avalanche center will have detailed 
forecasts and snowpack discussion. Always check the forecast with your local
avalanche center before you head out.</p>
        <%= button_to 'Find your forecast', 'https://avalanche.org', class: "btn btn-secondary btn-lg", method: :get %>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-4 card-bg border rounded-3">
          <h2>Take an avalanche safety course</h2>
          <p>Forecasts are just one aspect of safe winter backcountry travel. It's 
important to get in-person training so you can confirm that your observations
 in the field align with the forecasts and so you can confidently make judgement
 calls. The best way to do that is with an in-person avalanche safety course.</p>
          <%= button_to 'Find a course', 'https://avtraining.org/upcoming-public-avalanche-training-courses/', class: "btn btn-outline-secondary", method: :get %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 card-bg border rounded-3">
          <h2>Hone your skills online</h2>
          <p>If you can't make it to an in-person course, we recommend completing the AvySavvy
 course through Avalanche.ca. It it is free and has a lot of useful and practical 
 information on safe backcountry travel.</p>
           <%= button_to 'Practice online', 'https://avysavvy.avalanche.ca/en-ca/', class: "btn btn-outline-secondary", method: :get %>
        </div>
      </div>
    </div>

  </div>
</main>

app/views/shared/_area_detailed.html.erb
<div class="area_information rounded-2 card-bg px-3">
  <h3><%= "Details for #{@area.name}" %></h3>

    <p>Today's Avalanche Risk: <%= @area.current_av_risk_string %></p>
    <p>Forecast expires: <%= @area.end_date %></p> <%# make this smaller font than forecast risk%>
    <p>Travel advice: <%= @area.description %></p>
  <table align="center" class="table table-sm table-striped  ml-4"style="max-width: 40rem;">
    <thead>
      <tr>
        <th><%= link_to 'Check the NWAC forecast', @area.url%></th>
      </tr>
    </thead>
    <tbody>
      <% i = 0 %>
      <% @area.av_forecast_string.each do |day| %>
        <tr>
          <td>Avalanche forecast for  <%= "#{(Date.today + i).strftime("%A")}: #{day}" %>
                <% i += 1 %></td>
        </tr>
      <% end  %>
    </tbody>
  </table>
</div>

app/views/shared/_areas_overview.html.erb
<div class="list-group list-group-flush">
  <% @areas.each do |area| %>
    <div class="d-flex w-100 align-items-center justify-content-between">
      <strong class="mb-1"><%= link_to area.name, area_path(area.id) %></strong>
      Current Avalanche Risk: <%= area.current_av_risk_string %>
      <p>Travel Advice: <%= area.description %></p>
    </div>
  <% end %>
</div>

app/views/shared/_upcoming_trips.html.erb
<div class="d-flex flex-column align-items-stretch rounded-2 card-bg flex-shrink-0" style="width: 380px;">

    <h3 class="px-2 py-2 opacity-100 fw-semibold">Upcoming trips</h3>
    <div class="list-group list-group-flush border-bottom scrollarea">
      <% @user_trips.each do |trip| %>
      <a href="<%=users_trip_path(trip.id)%>" class="list-group-item list-group-item-action py-3 lh-sm">
        <div class="d-flex w-100 align-items-center justify-content-between">
          <strong class="mb-1"><%= trip.name %></strong>
          <small><%= trip.start_date %></small>
        </div>
        <div class="col-10 mb-1 small"> <%= trip.description %> </div>
      </a>
      <% end %>
    </div>

<%= button_to 'Add a new trip', new_users_trip_path, method: :get, local: true, class: "btn btn-sm btn-secondary mt-1 border-black bg-white text-black" %>
</div>

app/views/shared/_zone_weather_forecast.html.erb
<div class="weather_forecast rounded-2 card-bg px-3">
  <h3>Weather Forecast For <%= @area.name %></h3>
  <p> <%= @area.lat%>, <%= @area.long%></p>


  <iframe width="650" height="450" src="https://embed.windy.com/embed2.html?lat=<%= @area.lat %>&lon=<%= @area.long %>&detailLat=<%= @area.lat %>&detailLon=<%= @area.long %>&width=650&height=450&zoom=10&level=surface&overlay=snowcover&product=ecmwf&menu=&message=true&marker=true&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=default&metricTemp=default&radarRange=-1" frameborder="0"></iframe>
</div>

app/views/trips/edit.html.erb
<main class="px-3">
  <div class="cover-container d-flex p-3 mx-auto flex-column">
    <h1> Edit <%= @trip.name %> </h1>
  </div>
<br>

  <div class="row">
    <div class="container col-lg-10 card-bg p-3">
      <%= form_with url: users_trip_path(@trip.id), method: :patch, local: true do |f| %>
        <%= f.hidden_field :user_id, value: @user.id %>
        <%= f.hidden_field :id, value: @trip.id %>
          <div class="mb-3">
              <%= f.label :name, 'Trip name', class: "form-label fw-bold" %>
              <%= f.text_field :name, value: @trip.name, class: 'form-control' %>
          </div>

          <div class="mb-3">
            <%= f.label :zone_id, 'Forecast zone', class: "form-label fw-bold" %>
            <%= f.select :zone_id, options_for_select(avalanche_zones, @trip.zone_id), class: 'form-control' %>
          </div>

          <div class="mb-3">
              <%= f.label :start_date, "Date:", class: 'form-label fw-bold' %>
              <%= f.date_field :start_date, value: @trip.start_date, class: 'form-control' %>
          </div>

          <div class="mb-3">
              <%= f.label :description, "Trip description:", class: 'form-label fw-bold' %>
              <%= f.text_area :description, value: @trip.description, class: 'form-control' %>
          </div>


            <%= f.submit 'Update', class: "btn btn-lg btn-secondary border-white bg-black" %>
      <% end %>
      </div>
    </div>
</main>

app/views/trips/new.html.erb
<main class="px-3">
  <div class="cover-container d-flex p-3 mx-auto flex-column">
    <h1>Create a Trip </h1>
  </div>
<br>

  <div class="row">
    <div class="container col-lg-10 card-bg p-3">
      <%= form_with url: users_trips_path(@user.id), local: true do |f| %>
        <%= f.hidden_field :user_id, value: @user.id %>
          <div class="mb-3">
              <%= f.label :name, 'Trip name', class: "form-label fw-bold" %>
              <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="mb-3">
            <%= f.label :zone_id, 'Forecast zone', class: "form-label fw-bold" %>
            <%= f.select :zone_id, options_for_select(avalanche_zones), class: 'form-control' %>
          </div>

          <div class="mb-3">
              <%= f.label :start_date, "Date:", class: 'form-label fw-bold' %>
              <%= f.date_field :start_date, class: 'form-control' %>
          </div>

          <div class="mb-3">
              <%= f.label :description, "Trip description:", class: 'form-label fw-bold' %>
              <%= f.text_area :description, class: 'form-control' %>
          </div>


            <%= f.submit 'Create', class: "btn btn-lg btn-secondary border-white bg-black" %>
      <% end %>
      </div>
    </div>
</main>

app/views/trips/show.html.erb
<main>
  <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center card-bg">
    <div class="trip_details col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-4 fw-normal">Your trip</h1>
      <p class="lead fw-normal"><%= @trip.name %></p>
      <p class="lead fw-normal"><%= @trip.start_date.strftime('%B %d, %Y') %></p>
      <p class="lead fw-normal"><%= @trip.description %></p>
      <%= button_to "Edit #{@trip.name}", edit_users_trip_path(@trip.id), class: "btn btn-outline-secondary", method: :get %>
    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <%= render 'shared/area_detailed' %>
      </div>

    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <%= render 'shared/upcoming_trips' %>
      </div>

    </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
   
        <%= render 'shared/zone_weather_forecast' %>
        
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<div class="vstack">
<h1 class="text-center fs-1"><%= @user.name %>'s Profile</h1>
<br>

<row>
<div class="zone">
<center><h2 class="fw-lighter">Favorite Zone</h2>
<%= form_with url: users_path, method: :patch, local: true  do |form| %>
  <%= form.hidden_field :id, value: @user.id %>
  <%= form.label :favorite_zone %>
  <%= form.select :favorite_zone, options_for_select(avalanche_zones, @user.favorite_zone) %>
  <%= form.submit "Update"%>
<% end %>
</center></div>
</row>
<br>

<row>
<center class="contacts">
<h2 class="fw-lighter">Emergency Contacts</h2>
<table align="center" class="table table-sm table-striped  ml-4"style="max-width: 40rem;">
  <thead>
    <tr>
      <th class="fw-lighter">Name</th>
      <th class="fw-lighter">Phone Number</th>
    </tr>
  </thead>
  <tbody>
    <% @emergency_contacts.each do |contact| %>
      <tr id="one_contact-<%= contact.id%>">
        <td><%= contact.name %></td>
        <td><%= number_to_phone(contact.phone_number, area_code: true) %></td>
        <td><%= button_to "Edit", edit_users_emergency_contact_path(contact.id), method: :get %></td>
        <td><%= button_to "Delete", users_emergency_contact_path(@user.id), params: { contact_id: contact.id }, method: :delete %></td>
      </tr>
    <% end  %>
  </tbody>
</table>
  <%= button_to 'Add an Emergency Contact', new_users_emergency_contact_path, method: :get, local: true %>
</center>
</row>

app/views/users/show.html.erb
<main class="px-3">
  <div class="cover-container d-flex p-3 mx-auto flex-column">
      <h1> <%= @user.name %>'s Dashboard</h1>
      <p> Favorite zone: <%= zone_id_to_name(@user.favorite_zone) %>
  </div>
  <div class="row">
    <div class="container col-md-4">
      <%= render 'shared/upcoming_trips' %>
    </div>
    <div class="container col-md-4">
      <%= render 'shared/area_detailed' %>
    </div>
  </div>
</main>